"""agent initiative: agent_suggestions table

Revision ID: 0103ddd98e13
Revises: 9e4b457a0b76
Create Date: 2026-10-04 02:23:02.773361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0103ddd98e13'
down_revision: Union[str, None] = '9e4b457a0b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_suggestions',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_agent', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_suggestions_agent_id_agents')),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_agent_suggestions_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_agent_suggestions_org_id_organizations')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_agent_suggestions_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_suggestions'))
    )
    op.create_index(op.f('ix_agent_suggestions_agent_id'), 'agent_suggestions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_suggestions_org_id'), 'agent_suggestions', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_suggestions_proposed_at'), 'agent_suggestions', ['proposed_at'], unique=False)
    op.create_index(op.f('ix_agent_suggestions_status'), 'agent_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_suggestions_task_id'), 'agent_suggestions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_agent_suggestions_task_id'), table_name='agent_suggestions')
    op.drop_index(op.f('ix_agent_suggestions_status'), table_name='agent_suggestions')
    op.drop_index(op.f('ix_agent_suggestions_proposed_at'), table_name='agent_suggestions')
    op.drop_index(op.f('ix_agent_suggestions_org_id'), table_name='agent_suggestions')
    op.drop_index(op.f('ix_agent_suggestions_agent_id'), table_name='agent_suggestions')
    op.drop_table('agent_suggestions')
