"""phases 3-8: goals, reports, oauth tokens, task.goal_id

Revision ID: 9e4b457a0b76
Revises: c097ef62460a
Create Date: 2026-10-03 20:34:17.344909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4b457a0b76'
down_revision: Union[str, None] = 'c097ef62460a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_org_id'), 'goals', ['org_id'], unique=False)
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_org_id'), 'oauth_tokens', ['org_id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_provider'), 'oauth_tokens', ['provider'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=40), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_org_id'), 'reports', ['org_id'], unique=False)
    op.create_index(op.f('ix_reports_report_date'), 'reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)

    if op.get_bind().dialect.name == "sqlite":
        # SQLite cannot ALTER-add a FK constraint; the column alone keeps the app
        # fully functional and the model-level FK still applies on Postgres.
        with op.batch_alter_table('tasks') as batch:
            batch.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
    else:
        op.add_column('tasks', sa.Column('goal_id', sa.Integer(), nullable=True))
        op.create_foreign_key('fk_tasks_goal_id_goals', 'tasks', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('tasks') as batch:
        batch.drop_column('goal_id')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_date'), table_name='reports')
    op.drop_index(op.f('ix_reports_org_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_oauth_tokens_provider'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_org_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_goals_status'), table_name='goals')
    op.drop_index(op.f('ix_goals_org_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
