"""initial schema: all core entities

Revision ID: c097ef62460a
Revises: 
Create Date: 2026-10-03 20:15:15.621834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c097ef62460a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('system_events',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('workflow_run_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index(op.f('ix_system_events_agent_id'), 'system_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_org_id'), 'system_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_system_events_task_id'), 'system_events', ['task_id'], unique=False)
    op.create_table('agents',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('permission_level', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_task_id', sa.Integer(), nullable=True),
    sa.Column('model_config', sa.JSON(), nullable=False),
    sa.Column('memory_access', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_agents_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_department'), 'agents', ['department'], unique=False)
    op.create_index(op.f('ix_agents_key'), 'agents', ['key'], unique=False)
    op.create_index(op.f('ix_agents_org_id'), 'agents', ['org_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('channels',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('niche', sa.String(length=200), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('brand_settings', sa.JSON(), nullable=False),
    sa.Column('content_rules', sa.JSON(), nullable=False),
    sa.Column('publishing_rules', sa.JSON(), nullable=False),
    sa.Column('research_sources', sa.JSON(), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_channels_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels'))
    )
    op.create_index(op.f('ix_channels_org_id'), 'channels', ['org_id'], unique=False)
    op.create_index(op.f('ix_channels_slug'), 'channels', ['slug'], unique=False)
    op.create_table('integrations',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_integrations_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    op.create_index(op.f('ix_integrations_key'), 'integrations', ['key'], unique=False)
    op.create_index(op.f('ix_integrations_org_id'), 'integrations', ['org_id'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_table('knowledge_entities',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_knowledge_entities_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_entities'))
    )
    op.create_index(op.f('ix_knowledge_entities_entity_type'), 'knowledge_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_knowledge_entities_org_id'), 'knowledge_entities', ['org_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entities_slug'), 'knowledge_entities', ['slug'], unique=False)
    op.create_table('research_sources',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_research_sources_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources'))
    )
    op.create_index(op.f('ix_research_sources_org_id'), 'research_sources', ['org_id'], unique=False)
    op.create_table('schedules',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_schedules_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index(op.f('ix_schedules_org_id'), 'schedules', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('workflows',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_workflows_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    op.create_index(op.f('ix_workflows_org_id'), 'workflows', ['org_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('sender_agent_id', sa.Integer(), nullable=True),
    sa.Column('receiver_agent_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_agent_messages_org_id_organizations')),
    sa.ForeignKeyConstraint(['receiver_agent_id'], ['agents.id'], name=op.f('fk_agent_messages_receiver_agent_id_agents')),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], name=op.f('fk_agent_messages_sender_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index(op.f('ix_agent_messages_org_id'), 'agent_messages', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_task_id'), 'agent_messages', ['task_id'], unique=False)
    op.create_table('agent_permissions',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=60), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_permissions_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_permissions'))
    )
    op.create_index(op.f('ix_agent_permissions_agent_id'), 'agent_permissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_permissions_permission'), 'agent_permissions', ['permission'], unique=False)
    op.create_table('audit_logs',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_logs_org_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('content_ideas',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('source_evidence', sa.JSON(), nullable=False),
    sa.Column('trend_evidence', sa.JSON(), nullable=False),
    sa.Column('complexity', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('why_selected', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_content_ideas_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_content_ideas_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_ideas'))
    )
    op.create_index(op.f('ix_content_ideas_channel_id'), 'content_ideas', ['channel_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_org_id'), 'content_ideas', ['org_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_status'), 'content_ideas', ['status'], unique=False)
    op.create_table('experiments',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('variable', sa.String(length=100), nullable=False),
    sa.Column('control', sa.Text(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_experiments_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_experiments_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_channel_id'), 'experiments', ['channel_id'], unique=False)
    op.create_index(op.f('ix_experiments_org_id'), 'experiments', ['org_id'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('knowledge_relationships',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_knowledge_relationships_org_id_organizations')),
    sa.ForeignKeyConstraint(['source_entity_id'], ['knowledge_entities.id'], name=op.f('fk_knowledge_relationships_source_entity_id_knowledge_entities')),
    sa.ForeignKeyConstraint(['target_entity_id'], ['knowledge_entities.id'], name=op.f('fk_knowledge_relationships_target_entity_id_knowledge_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_relationships'))
    )
    op.create_index(op.f('ix_knowledge_relationships_org_id'), 'knowledge_relationships', ['org_id'], unique=False)
    op.create_index(op.f('ix_knowledge_relationships_relation_type'), 'knowledge_relationships', ['relation_type'], unique=False)
    op.create_index(op.f('ix_knowledge_relationships_source_entity_id'), 'knowledge_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_relationships_target_entity_id'), 'knowledge_relationships', ['target_entity_id'], unique=False)
    op.create_table('learning_insights',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_learning_insights_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_learning_insights_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_insights'))
    )
    op.create_index(op.f('ix_learning_insights_channel_id'), 'learning_insights', ['channel_id'], unique=False)
    op.create_index(op.f('ix_learning_insights_org_id'), 'learning_insights', ['org_id'], unique=False)
    op.create_index(op.f('ix_learning_insights_status'), 'learning_insights', ['status'], unique=False)
    op.create_table('memories',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_memories_agent_id_agents')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_memories_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_memories_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index(op.f('ix_memories_agent_id'), 'memories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_memories_channel_id'), 'memories', ['channel_id'], unique=False)
    op.create_index(op.f('ix_memories_idea_id'), 'memories', ['idea_id'], unique=False)
    op.create_index(op.f('ix_memories_org_id'), 'memories', ['org_id'], unique=False)
    op.create_index(op.f('ix_memories_scope'), 'memories', ['scope'], unique=False)
    op.create_table('research_documents',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('credibility', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_research_documents_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_research_documents_org_id_organizations')),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], name=op.f('fk_research_documents_source_id_research_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_documents'))
    )
    op.create_index(op.f('ix_research_documents_channel_id'), 'research_documents', ['channel_id'], unique=False)
    op.create_index(op.f('ix_research_documents_org_id'), 'research_documents', ['org_id'], unique=False)
    op.create_index('ix_research_documents_org_topic', 'research_documents', ['org_id', 'topic'], unique=False)
    op.create_index(op.f('ix_research_documents_retrieved_at'), 'research_documents', ['retrieved_at'], unique=False)
    op.create_index(op.f('ix_research_documents_topic'), 'research_documents', ['topic'], unique=False)
    op.create_table('tasks',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workflow_run_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], name=op.f('fk_tasks_assigned_agent_id_agents')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_tasks_channel_id_channels')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_tasks_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_tasks_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_assigned_agent_id'), 'tasks', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_channel_id'), 'tasks', ['channel_id'], unique=False)
    op.create_index(op.f('ix_tasks_idea_id'), 'tasks', ['idea_id'], unique=False)
    op.create_index(op.f('ix_tasks_org_id'), 'tasks', ['org_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_workflow_run_id'), 'tasks', ['workflow_run_id'], unique=False)
    op.create_table('topics',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_topics_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_topics_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index(op.f('ix_topics_channel_id'), 'topics', ['channel_id'], unique=False)
    op.create_index(op.f('ix_topics_org_id'), 'topics', ['org_id'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=False)
    op.create_table('trends',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lifecycle', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_trends_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_trends_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trends'))
    )
    op.create_index(op.f('ix_trends_channel_id'), 'trends', ['channel_id'], unique=False)
    op.create_index(op.f('ix_trends_last_updated'), 'trends', ['last_updated'], unique=False)
    op.create_index(op.f('ix_trends_lifecycle'), 'trends', ['lifecycle'], unique=False)
    op.create_index(op.f('ix_trends_org_id'), 'trends', ['org_id'], unique=False)
    op.create_index(op.f('ix_trends_topic'), 'trends', ['topic'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_workflow_runs_org_id_organizations')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_runs_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    op.create_index(op.f('ix_workflow_runs_org_id'), 'workflow_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_runs_agent_id_agents')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_agent_runs_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_id'), 'agent_runs', ['task_id'], unique=False)
    op.create_table('approvals',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_approvals_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], name=op.f('fk_approvals_idea_id_content_ideas')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_approvals_org_id_organizations')),
    sa.ForeignKeyConstraint(['requested_by_agent_id'], ['agents.id'], name=op.f('fk_approvals_requested_by_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_idea_id'), 'approvals', ['idea_id'], unique=False)
    op.create_index(op.f('ix_approvals_org_id'), 'approvals', ['org_id'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=60), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.id'], name=op.f('fk_assets_created_by_agent_id_agents')),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], name=op.f('fk_assets_idea_id_content_ideas')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_assets_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_idea_id'), 'assets', ['idea_id'], unique=False)
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_table('claims',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('script_version_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reviewer_agent_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], name=op.f('fk_claims_idea_id_content_ideas')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_claims_org_id_organizations')),
    sa.ForeignKeyConstraint(['reviewer_agent_id'], ['agents.id'], name=op.f('fk_claims_reviewer_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index(op.f('ix_claims_idea_id'), 'claims', ['idea_id'], unique=False)
    op.create_index(op.f('ix_claims_org_id'), 'claims', ['org_id'], unique=False)
    op.create_index(op.f('ix_claims_script_version_id'), 'claims', ['script_version_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('cost_records',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_cost_records_agent_id_agents')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_cost_records_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cost_records_org_id_organizations')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_cost_records_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_records'))
    )
    op.create_index(op.f('ix_cost_records_category'), 'cost_records', ['category'], unique=False)
    op.create_index(op.f('ix_cost_records_occurred_at'), 'cost_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_cost_records_org_id'), 'cost_records', ['org_id'], unique=False)
    op.create_table('experiment_results',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_results_experiment_id_experiments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_results'))
    )
    op.create_index(op.f('ix_experiment_results_experiment_id'), 'experiment_results', ['experiment_id'], unique=False)
    op.create_table('production_jobs',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], name=op.f('fk_production_jobs_idea_id_content_ideas')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_production_jobs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_jobs'))
    )
    op.create_index(op.f('ix_production_jobs_idea_id'), 'production_jobs', ['idea_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_org_id'), 'production_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_status'), 'production_jobs', ['status'], unique=False)
    op.create_table('publishing_jobs',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('video_id', sa.String(length=200), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_publishing_jobs_channel_id_channels')),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], name=op.f('fk_publishing_jobs_idea_id_content_ideas')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_publishing_jobs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishing_jobs'))
    )
    op.create_index(op.f('ix_publishing_jobs_channel_id'), 'publishing_jobs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_idea_id'), 'publishing_jobs', ['idea_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_org_id'), 'publishing_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_status'), 'publishing_jobs', ['status'], unique=False)
    op.create_table('quality_checks',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], name=op.f('fk_quality_checks_idea_id_content_ideas')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_quality_checks_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_checks'))
    )
    op.create_index(op.f('ix_quality_checks_idea_id'), 'quality_checks', ['idea_id'], unique=False)
    op.create_index(op.f('ix_quality_checks_org_id'), 'quality_checks', ['org_id'], unique=False)
    op.create_index(op.f('ix_quality_checks_result'), 'quality_checks', ['result'], unique=False)
    op.create_table('scripts',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], name=op.f('fk_scripts_idea_id_content_ideas')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_scripts_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripts'))
    )
    op.create_index(op.f('ix_scripts_idea_id'), 'scripts', ['idea_id'], unique=False)
    op.create_index(op.f('ix_scripts_org_id'), 'scripts', ['org_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], name=op.f('fk_task_dependencies_depends_on_id_tasks')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_dependencies')),
    sa.UniqueConstraint('task_id', 'depends_on_id', name='uq_task_dep_unique')
    )
    op.create_index(op.f('ix_task_dependencies_depends_on_id'), 'task_dependencies', ['depends_on_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('publishing_job_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('video_title', sa.String(length=400), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('watch_time_minutes', sa.Float(), nullable=False),
    sa.Column('retention_pct', sa.Float(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_analytics_snapshots_channel_id_channels')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_analytics_snapshots_org_id_organizations')),
    sa.ForeignKeyConstraint(['publishing_job_id'], ['publishing_jobs.id'], name=op.f('fk_analytics_snapshots_publishing_job_id_publishing_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_snapshots'))
    )
    op.create_index(op.f('ix_analytics_snapshots_captured_at'), 'analytics_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_channel_id'), 'analytics_snapshots', ['channel_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_org_id'), 'analytics_snapshots', ['org_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_publishing_job_id'), 'analytics_snapshots', ['publishing_job_id'], unique=False)
    op.create_table('rights_records',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('content_description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('license_ref', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_rights_records_asset_id_assets')),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], name=op.f('fk_rights_records_idea_id_content_ideas')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_rights_records_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rights_records'))
    )
    op.create_index(op.f('ix_rights_records_asset_id'), 'rights_records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_rights_records_idea_id'), 'rights_records', ['idea_id'], unique=False)
    op.create_index(op.f('ix_rights_records_org_id'), 'rights_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_rights_records_status'), 'rights_records', ['status'], unique=False)
    op.create_table('script_versions',
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author_agent_id', sa.Integer(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('transitions', sa.Text(), nullable=False),
    sa.Column('ending', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('pacing', sa.JSON(), nullable=False),
    sa.Column('visual_suggestions', sa.JSON(), nullable=False),
    sa.Column('narration_notes', sa.Text(), nullable=False),
    sa.Column('on_screen_text', sa.JSON(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_agent_id'], ['agents.id'], name=op.f('fk_script_versions_author_agent_id_agents')),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_script_versions_script_id_scripts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_versions'))
    )
    op.create_index(op.f('ix_script_versions_script_id'), 'script_versions', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_versions_script_id'), table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index(op.f('ix_rights_records_status'), table_name='rights_records')
    op.drop_index(op.f('ix_rights_records_org_id'), table_name='rights_records')
    op.drop_index(op.f('ix_rights_records_idea_id'), table_name='rights_records')
    op.drop_index(op.f('ix_rights_records_asset_id'), table_name='rights_records')
    op.drop_table('rights_records')
    op.drop_index(op.f('ix_analytics_snapshots_publishing_job_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_org_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_channel_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_captured_at'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_scripts_org_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_idea_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_quality_checks_result'), table_name='quality_checks')
    op.drop_index(op.f('ix_quality_checks_org_id'), table_name='quality_checks')
    op.drop_index(op.f('ix_quality_checks_idea_id'), table_name='quality_checks')
    op.drop_table('quality_checks')
    op.drop_index(op.f('ix_publishing_jobs_status'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_org_id'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_idea_id'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_channel_id'), table_name='publishing_jobs')
    op.drop_table('publishing_jobs')
    op.drop_index(op.f('ix_production_jobs_status'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_org_id'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_idea_id'), table_name='production_jobs')
    op.drop_table('production_jobs')
    op.drop_index(op.f('ix_experiment_results_experiment_id'), table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_index(op.f('ix_cost_records_org_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_occurred_at'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_category'), table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_script_version_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_org_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_idea_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_idea_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_org_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_idea_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_runs_task_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_org_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_trends_topic'), table_name='trends')
    op.drop_index(op.f('ix_trends_org_id'), table_name='trends')
    op.drop_index(op.f('ix_trends_lifecycle'), table_name='trends')
    op.drop_index(op.f('ix_trends_last_updated'), table_name='trends')
    op.drop_index(op.f('ix_trends_channel_id'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_org_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_channel_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_tasks_workflow_run_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_org_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_idea_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_channel_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_agent_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_research_documents_topic'), table_name='research_documents')
    op.drop_index(op.f('ix_research_documents_retrieved_at'), table_name='research_documents')
    op.drop_index('ix_research_documents_org_topic', table_name='research_documents')
    op.drop_index(op.f('ix_research_documents_org_id'), table_name='research_documents')
    op.drop_index(op.f('ix_research_documents_channel_id'), table_name='research_documents')
    op.drop_table('research_documents')
    op.drop_index(op.f('ix_memories_scope'), table_name='memories')
    op.drop_index(op.f('ix_memories_org_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_idea_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_channel_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_agent_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_learning_insights_status'), table_name='learning_insights')
    op.drop_index(op.f('ix_learning_insights_org_id'), table_name='learning_insights')
    op.drop_index(op.f('ix_learning_insights_channel_id'), table_name='learning_insights')
    op.drop_table('learning_insights')
    op.drop_index(op.f('ix_knowledge_relationships_target_entity_id'), table_name='knowledge_relationships')
    op.drop_index(op.f('ix_knowledge_relationships_source_entity_id'), table_name='knowledge_relationships')
    op.drop_index(op.f('ix_knowledge_relationships_relation_type'), table_name='knowledge_relationships')
    op.drop_index(op.f('ix_knowledge_relationships_org_id'), table_name='knowledge_relationships')
    op.drop_table('knowledge_relationships')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_org_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_channel_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_content_ideas_status'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_org_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_channel_id'), table_name='content_ideas')
    op.drop_table('content_ideas')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_permissions_permission'), table_name='agent_permissions')
    op.drop_index(op.f('ix_agent_permissions_agent_id'), table_name='agent_permissions')
    op.drop_table('agent_permissions')
    op.drop_index(op.f('ix_agent_messages_task_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_org_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_workflows_org_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schedules_org_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_research_sources_org_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_knowledge_entities_slug'), table_name='knowledge_entities')
    op.drop_index(op.f('ix_knowledge_entities_org_id'), table_name='knowledge_entities')
    op.drop_index(op.f('ix_knowledge_entities_entity_type'), table_name='knowledge_entities')
    op.drop_table('knowledge_entities')
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_org_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_key'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_channels_slug'), table_name='channels')
    op.drop_index(op.f('ix_channels_org_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_org_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_key'), table_name='agents')
    op.drop_index(op.f('ix_agents_department'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_system_events_task_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_org_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_agent_id'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
