"""The AI organization: 33 agents across 8 departments (Section 8).

Pure configuration - agents are data, not code. Adding an agent here
seeds it into every new organization automatically.
"""
from typing import Any

AgentDef = dict[str, Any]

AGENTS: list[AgentDef] = [
    # --- Executive ---
    {"key": "chief_strategy", "name": "Chief Strategy Agent", "department": "executive",
     "role": "Sets company-wide content strategy, prioritizes across channels",
     "description": "Synthesizes trends, performance and goals into weekly strategy and picks what gets made.",
     "capabilities": ["strategy", "synthesis", "prioritization"], "tools": ["memory", "knowledge", "trends", "analytics"],
     "permission_level": "reviewer"},
    {"key": "chief_operations", "name": "Chief Operations Agent", "department": "executive",
     "role": "Coordinates all departments and keeps the pipeline flowing",
     "description": "Breaks goals into tasks, assigns agents, tracks progress, escalates blockers.",
     "capabilities": ["planning", "coordination", "escalation"], "tools": ["tasks", "memory", "events"],
     "permission_level": "reviewer"},
    {"key": "project_manager", "name": "Project Manager Agent", "department": "executive",
     "role": "Manages individual content projects end to end",
     "description": "Owns a piece of content from idea to publish: deadlines, dependencies, handoffs.",
     "capabilities": ["project_tracking", "scheduling", "dependencies"], "tools": ["tasks", "memory"],
     "permission_level": "worker"},

    # --- Intelligence ---
    {"key": "web_research", "name": "Web Research Agent", "department": "intelligence",
     "role": "Researches topics across the open web",
     "description": "Finds documents and sources for topics using configured research providers.",
     "capabilities": ["web_research"], "tools": ["web_search", "knowledge"],
     "permission_level": "worker"},
    {"key": "trend_intelligence", "name": "Trend Intelligence Agent", "department": "intelligence",
     "role": "Detects and scores emerging trends",
     "description": "Runs the Trend Radar: combines multiple signals into documented trend scores.",
     "capabilities": ["trend_analysis", "signal_scoring"], "tools": ["trends", "web_search", "analytics"],
     "permission_level": "worker"},
    {"key": "social_intelligence", "name": "Social Intelligence Agent", "department": "intelligence",
     "role": "Monitors social platforms as trend-discovery signals",
     "description": "Treats social chatter as a signal, never as factual evidence (Section 14).",
     "capabilities": ["social_listening"], "tools": ["web_search"],
     "permission_level": "read_only"},
    {"key": "competitor_intelligence", "name": "Competitor Intelligence Agent", "department": "intelligence",
     "role": "Watches competitor channels and content",
     "description": "Tracks what competitor channels publish and what performs for them.",
     "capabilities": ["competitor_analysis"], "tools": ["youtube", "analytics"],
     "permission_level": "read_only"},
    {"key": "fact_verification", "name": "Fact Verification Agent", "department": "intelligence",
     "role": "Verifies factual claims against sources",
     "description": "Assigns claim-level verification states and confidence with cited sources.",
     "capabilities": ["fact_checking", "source_evaluation"], "tools": ["web_search", "knowledge"],
     "permission_level": "reviewer"},
    {"key": "source_evaluation", "name": "Source Evaluation Agent", "department": "intelligence",
     "role": "Ranks sources by credibility and type",
     "description": "Applies the source hierarchy (primary > official > research > journalism > social).",
     "capabilities": ["credibility_assessment"], "tools": ["knowledge"],
     "permission_level": "reviewer"},

    # --- Creative ---
    {"key": "idea", "name": "Idea Agent", "department": "creative",
     "role": "Generates content ideas from research and trends",
     "description": "Turns trend + source evidence into concrete Shorts ideas with hooks.",
     "capabilities": ["ideation"], "tools": ["memory", "knowledge", "trends"],
     "permission_level": "worker"},
    {"key": "hook", "name": "Hook Agent", "department": "creative",
     "role": "Crafts the first-3-seconds hook",
     "description": "Specializes in opening lines that stop the scroll.",
     "capabilities": ["hook_writing"], "tools": ["memory"],
     "permission_level": "worker"},
    {"key": "script", "name": "Script Agent", "department": "creative",
     "role": "Writes full Shorts scripts",
     "description": "Writes pacing-aware scripts with body, transitions, ending and CTA.",
     "capabilities": ["script_writing"], "tools": ["memory", "knowledge"],
     "permission_level": "worker"},
    {"key": "storytelling", "name": "Storytelling Agent", "department": "creative",
     "role": "Improves narrative structure",
     "description": "Restructures scripts for tension, payoff and retention.",
     "capabilities": ["narrative_design"], "tools": ["memory"],
     "permission_level": "worker"},
    {"key": "content_strategist", "name": "Content Strategist Agent", "department": "creative",
     "role": "Plans channel content calendars",
     "description": "Builds weekly content plans per channel from strategy and trend data.",
     "capabilities": ["content_planning"], "tools": ["memory", "trends", "analytics"],
     "permission_level": "worker"},

    # --- Production ---
    {"key": "production_planner", "name": "Production Planner Agent", "department": "production",
     "role": "Builds production plans for approved ideas",
     "description": "Chooses providers, assets and steps; estimates complexity and cost.",
     "capabilities": ["production_planning"], "tools": ["tasks", "costs"],
     "permission_level": "worker"},
    {"key": "video_generation", "name": "Video Generation Agent", "department": "production",
     "role": "Drives configured video-generation providers",
     "description": "Submits production jobs through the VideoProvider abstraction (Section 22).",
     "capabilities": ["video_generation"], "tools": ["video_provider"],
     "permission_level": "worker"},
    {"key": "editing", "name": "Editing Agent", "department": "production",
     "role": "Handles post-production editing",
     "description": "Cuts, sequences and polishes produced assets.",
     "capabilities": ["editing"], "tools": ["video_provider"],
     "permission_level": "worker"},
    {"key": "caption", "name": "Caption Agent", "department": "production",
     "role": "Generates captions/subtitles",
     "description": "Produces timed captions aligned to narration.",
     "capabilities": ["captions"], "tools": [],
     "permission_level": "worker"},
    {"key": "thumbnail_visual", "name": "Thumbnail/Visual Agent", "department": "production",
     "role": "Creates thumbnails and key visuals",
     "description": "Designs covers and on-screen visual concepts in brand style.",
     "capabilities": ["visual_design"], "tools": [],
     "permission_level": "worker"},

    # --- Quality ---
    {"key": "fact_checker", "name": "Fact Checker Agent", "department": "quality",
     "role": "Final pre-publish factual gate",
     "description": "Blocks publishing while required claims remain unresolved (Section 19).",
     "capabilities": ["fact_checking"], "tools": ["web_search", "knowledge"],
     "permission_level": "reviewer"},
    {"key": "copyright_rights", "name": "Copyright/Rights Agent", "department": "quality",
     "role": "Manages rights records for all third-party media",
     "description": "Blocks publishing when rights status is unknown or blocked (Section 21).",
     "capabilities": ["rights_management"], "tools": ["knowledge"],
     "permission_level": "reviewer"},
    {"key": "quality_control", "name": "Quality Control Agent", "department": "quality",
     "role": "Runs automated QC on every video",
     "description": "Returns PASS / FAIL / NEEDS_REVIEW with documented reasons (Section 23).",
     "capabilities": ["qc"], "tools": ["tasks"],
     "permission_level": "reviewer"},
    {"key": "brand_safety", "name": "Brand Safety Agent", "department": "quality",
     "role": "Guards channel voice and safety rules",
     "description": "Checks content against channel-specific brand rules.",
     "capabilities": ["brand_safety"], "tools": ["memory"],
     "permission_level": "reviewer"},

    # --- Publishing ---
    {"key": "publishing", "name": "Publishing Agent", "department": "publishing",
     "role": "Executes approved publishing jobs",
     "description": "Uploads to YouTube via the publishing integration after approval. Cannot act without it.",
     "capabilities": ["publishing"], "tools": ["youtube_publisher"],
     "permission_level": "publisher"},
    {"key": "scheduling", "name": "Scheduling Agent", "department": "publishing",
     "role": "Picks optimal publish times",
     "description": "Schedules publishing jobs per channel publishing rules.",
     "capabilities": ["scheduling"], "tools": ["analytics"],
     "permission_level": "publisher"},
    {"key": "metadata", "name": "Metadata Agent", "department": "publishing",
     "role": "Writes titles, descriptions, tags",
     "description": "Optimizes metadata within channel rules - never misleading metadata.",
     "capabilities": ["metadata_writing"], "tools": [],
     "permission_level": "worker"},

    # --- Growth ---
    {"key": "analytics", "name": "Analytics Agent", "department": "growth",
     "role": "Collects and interprets performance metrics",
     "description": "Builds composite performance analysis, not views-only (Section 26).",
     "capabilities": ["analytics"], "tools": ["analytics", "youtube"],
     "permission_level": "read_only"},
    {"key": "experiment", "name": "Experiment Agent", "department": "growth",
     "role": "Designs and runs experiments",
     "description": "A/B tests hooks, titles, pacing with tracked hypotheses and limitations (Section 27).",
     "capabilities": ["experimentation"], "tools": ["analytics"],
     "permission_level": "worker"},
    {"key": "optimization", "name": "Optimization Agent", "department": "growth",
     "role": "Turns insights into channel improvements",
     "description": "Applies learning insights to future content decisions.",
     "capabilities": ["optimization"], "tools": ["memory", "analytics"],
     "permission_level": "worker"},
    {"key": "audience_intelligence", "name": "Audience Intelligence Agent", "department": "growth",
     "role": "Models what the audience wants",
     "description": "Analyzes retention and engagement patterns per channel.",
     "capabilities": ["audience_analysis"], "tools": ["analytics"],
     "permission_level": "read_only"},

    # --- Operations / Finance ---
    {"key": "cost_intelligence", "name": "Cost Intelligence Agent", "department": "operations",
     "role": "Tracks spend against budgets",
     "description": "Monitors cost per video/channel/experiment and enforces limits (Section 30).",
     "capabilities": ["cost_tracking"], "tools": ["costs"],
     "permission_level": "read_only"},
    {"key": "system_health", "name": "System Health Agent", "department": "operations",
     "role": "Watches integration health and failures",
     "description": "Reports integration status, failed tasks and event anomalies (Section 36).",
     "capabilities": ["health_monitoring"], "tools": ["events", "tasks"],
     "permission_level": "read_only"},
    {"key": "daily_report", "name": "Daily Report Agent", "department": "operations",
     "role": "Produces the daily executive report",
     "description": "Generates reports from actual stored data only (Section 32).",
     "capabilities": ["reporting"], "tools": ["analytics", "tasks", "costs", "trends"],
     "permission_level": "read_only"},
]

DEPARTMENTS = ["executive", "intelligence", "creative", "production", "quality", "publishing", "growth", "operations"]


def get_agent_def(key: str) -> AgentDef | None:
    return next((a for a in AGENTS if a["key"] == key), None)
