"""Canonical system event types (Section 39 of the specification)."""


class EventType:
    # Task lifecycle
    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_BLOCKED = "TASK_BLOCKED"

    # Agent lifecycle
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    AGENT_PAUSED = "AGENT_PAUSED"
    AGENT_RESUMED = "AGENT_RESUMED"

    # Research / trends
    RESEARCH_COMPLETED = "RESEARCH_COMPLETED"
    RESEARCH_FAILED = "RESEARCH_FAILED"
    TREND_DETECTED = "TREND_DETECTED"

    # Content pipeline
    CONTENT_CREATED = "CONTENT_CREATED"
    IDEA_APPROVED = "IDEA_APPROVED"
    SCRIPT_READY = "SCRIPT_READY"
    FACT_CHECK_FAILED = "FACT_CHECK_FAILED"
    QC_PASSED = "QC_PASSED"
    QC_FAILED = "QC_FAILED"

    # Approval / publishing
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    VIDEO_PUBLISHED = "VIDEO_PUBLISHED"
    PUBLISH_FAILED = "PUBLISH_FAILED"

    # Platform
    ANALYTICS_UPDATED = "ANALYTICS_UPDATED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    OPERATIONS_PAUSED = "OPERATIONS_PAUSED"
    OPERATIONS_RESUMED = "OPERATIONS_RESUMED"
    INTEGRATION_STATUS_CHANGED = "INTEGRATION_STATUS_CHANGED"
    ORG_REGISTERED = "ORG_REGISTERED"
